name: All dependencies are up to date

on:
  schedule:
    # Schedule to run every night at 02:46
    - cron:  '46 2 * * *'
  workflow_dispatch:
  push:
    branches:
    - main

env:
  git_repos: ("novnc/noVNC" "novnc/websockify")
  docker_repos: ("alpine")

jobs:
  check-dependencies-versions:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Get external repository tags
      run: |
        . .github/workflows/utils.sh
        declare -a repos=${git_repos}

        for repo in "${repos[@]}"
        do
          # Fetch all tags
          tags=$(curl -s https://api.github.com/repos/${repo}/tags?per_page=5)
          # Get the latest tag
          latest_tag=$(echo $tags | jq -r '[.[] | select(.name | test("-beta"; "i") | not) | .name][0]')
          echo "$(normalise ${repo})_LATEST_TAG=${latest_tag}" >> $GITHUB_ENV
        done

    - name: Get latest version of Docker image
      run: |
        . .github/workflows/utils.sh
        declare -a repos=${docker_repos}

        for repo in "${repos[@]}"
        do
          # Fetch all tags
          tags=$(curl https://registry.hub.docker.com/v2/repositories/library/${repo}/tags?page_size=5)
          # Get the latest tag
          latest_tag=$(echo $tags | jq -r '[.results[] | select(.name | test("latest"; "i") | not) | select(.name | test("rc"; "i") | not) | select(.name | test("edge"; "i") | not) | .name][0]')
          echo "$(normalise ${repo})_LATEST_TAG=${latest_tag}" >> $GITHUB_ENV
        done

    - name: Compare tags to .env file
      id: check_tags
      run: |
        . .github/workflows/utils.sh
        declare -a git_repo=${git_repos}
        declare -a docker_repo=${docker_repos}
        declare -a repos=("${git_repo[@]}" "${docker_repo[@]}")
        changes=false
        version_message="Out of date dependencies:"

        for repo in "${repos[@]}"
        do
          repo=$(normalise ${repo})
          env_tag=$(grep ${repo}_TAG .env | awk -F '=' '{print $2}')
          latest_tag_key=$(echo ${repo}_LATEST_TAG)
          latest_tag=${!latest_tag_key}
          echo "Checking ${repo} has a new tag - current: ${env_tag}, new ${latest_tag}"
          if [ $env_tag != $latest_tag ]; then
              changes=true
              version_message=" ${version_message} ${repo}_TAG=${latest_tag}"
          fi
        done
        echo "has_changes=${changes}" >> $GITHUB_ENV
        echo "version_message=${version_message}" >> $GITHUB_ENV

    - name: Fail if there are any version differences
      if: ${{ env.has_changes == 'true' }}
      run: |
        echo "${version_message}"
        exit 1
